jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install
      - run:
          name: Test
          command: |
            composer test
            git status
            git status | grep "nothing to commit, working tree clean"

version: 2
