name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        php: [ '7.4', '8.0', '8.1', '8.2' ]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}
        extensions: pdo, inotify

    - name: Install
      run: |
        composer install

    - name: Test
      run: |
        composer test
        git status
        git status | grep "nothing to commit, working tree clean"
